version: "3"
services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: tasklist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  postgres-test:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: tasklist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"