--liquibase formatted sql

--changeset migration:1.0 context:local,dev,test,qa,prod
CREATE SCHEMA TASKLIST AUTHORIZATION postgres;
--rollback DROP SCHEMA TASKLIST

--changeset migration:1 context:local,dev,test,qa,prod
CREATE TABLE TASKLIST.TASKS (
    ID UUID NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DH_CREATE TIMESTAMP(6),
    CONSTRAINT TASKS_PK PRIMARY KEY(ID)
);
--rollback DROP TABLE TASKLIST.TASKS;

--changeset migration:2 context:local,dev,test,qa,prod
COMMENT ON COLUMN TASKLIST.TASKS.ID IS 'ID OF TASK';
COMMENT ON COLUMN TASKLIST.TASKS.TITLE IS 'TITLE OF TASK';
COMMENT ON COLUMN TASKLIST.TASKS.DESCRIPTION IS 'DESCRIPTION OF TASK';
COMMENT ON COLUMN TASKLIST.TASKS.STATUS IS 'STATUS OF TASK';
COMMENT ON COLUMN TASKLIST.TASKS.DH_CREATE IS 'DATE OF CREATION OF TASK';
--rollback not required

--changeset migration:3 context:local,dev,test,qa,prod
CREATE OR REPLACE VIEW TASKLIST.VW_TASKS AS SELECT * FROM TASKLIST.TASKS;
--rollback DROP VIEW TASKLIST.VW_TASKS;